name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        architecture: [x64]
        python-version: ['3.9']
      fail-fast: false
    name: Test ${{ matrix.os }} ${{ matrix.architecture }}
      Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rms_env
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: "latest"
          python-version: ${{ matrix.python-version }}
          use-mamba: true
      - name: Install packages
        run: |
          python -m pip install pytest nbmake
          python -m pip install -e .
      - name: Conda Info
        run: |
          mamba info
          mamba list
      - name: Run test
        run: |
          nosetests pyrms/rmsTest.py
          pytest --nbmake Ipython/pyrms_example.ipynb